service: posture-detection-backend

frameworkVersion: '3'

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

#plugins:
#  - serverless-offline
#  - serverless-jetpack
#  - serverless-dotenv-plugin
#  - serverless-plugin-include-dependencies
#  - serverless-plugin-common-excludes




#custom:
#  bundle:
#    ignorePackages:
#      - pg-native
#  includeDependencies:
#    includeAll: true
#
#common-excludes: true
#
#package:
#  individually: true
#  exclude:
#    - '**/node_modules/aws-sdk/**'
#    - '**/node_modules/**/test/**'
#    - '**/node_modules/**/README.*'
#  include:
#    - '!**/node_modules/aws-sdk/**'
#    - .env